export enum SVGEnum {
 headerBell = "assets/_hi-point/svg/header-bell.svg",
 headerAvatar = "assets/_hi-point/svg/header-avatar.svg",
 headerHam = "assets/_hi-point/svg/header-ham.svg",
 sensorTemp = "assets/_hi-point/svg/sensor-card/temp.svg",
 sensorHumidity = "assets/_hi-point/svg/sensor-card/humidity.svg",
 sensorKW = "assets/_hi-point/svg/sensor-card/kw.svg",
 sensorPar = "assets/_hi-point/svg/sensor-card/par.svg",
 sensorLux = "assets/_hi-point/svg/sensor-card/lux.svg",
 sensorSoil = "assets/_hi-point/svg/sensor-card/soil.svg",
 duoHistory = "assets/_hi-point/svg/duo/history.svg",
 fsMagnifyingGlass = "assets/_hi-point/svg/font/magnifying-glass-solid.svg",
 gallery = "assets/_hi-point/svg/gallery.svg",
 cloud1 = "assets/_hi-point/svg/cloud1.svg",
 calendar1 = "assets/_hi-point/svg/calendar1.svg",
 xMark = "assets/_hi-point/svg/x-mark.svg",
 arrowsExchange = "assets/_hi-point/svg/arrows-exchange.svg",
 circleArrow = "assets/_hi-point/svg/circle-arrow.svg",
 yuBan = "assets/_hi-point/svg/yuBan.svg",
 addCross = "assets/_hi-point/svg/add-cross.svg",
}
